
# Applications
appbuild_admin_application_list:
    path:     '/'
    defaults: { _controller: 'AppbuildApplicationBundle:Admin/Application:list' }

appbuild_admin_application_create:
    path:     '/create'
    defaults: { _controller: 'AppbuildApplicationBundle:Admin/Application:create' }

appbuild_admin_application_update:
    path:     '/{id}/update'
    defaults: { _controller: 'AppbuildApplicationBundle:Admin/Application:update' }

appbuild_admin_application_delete:
    path:     '/{id}/delete'
    defaults: { _controller: 'AppbuildApplicationBundle:Admin/Application:delete' }

appbuild_admin_application_toggle_enable:
    path:     '/{id}/enable'
    defaults: { _controller: 'AppbuildApplicationBundle:Admin/Application:toggleEnable' }
