
# Builds
majoraotastore_admin_build_list:
    path:     '/'
    defaults: { _controller: 'MajoraOTAStoreApplicationBundle:Admin/Build:list' }

majoraotastore_admin_build_create:
    path:     '/create'
    defaults: { _controller: 'MajoraOTAStoreApplicationBundle:Admin/Build:create' }

majoraotastore_admin_build_update:
    path:     '/{id}/update'
    defaults: { _controller: 'MajoraOTAStoreApplicationBundle:Admin/Build:update' }

majoraotastore_admin_build_delete:
    path:     '/{id}/delete'
    defaults: { _controller: 'MajoraOTAStoreApplicationBundle:Admin/Build:delete' }

majoraotastore_admin_build_upload:
    path:     '/upload'
    defaults: { _controller: 'MajoraOTAStoreApplicationBundle:Admin/Build:uploadAjax' }

majoraotastore_admin_build_download:
    path:     '/{id}/download'
    defaults: { _controller: 'MajoraOTAStoreApplicationBundle:Admin/Build:download' }

majoraotastore_admin_build_get_manifest:
    path:     '/{id}/manifest'
    defaults: { _controller: 'MajoraOTAStoreApplicationBundle:Admin/Build:getManifest' }

majoraotastore_admin_build_get_file:
    path:     '/{id}/file'
    defaults: { _controller: 'MajoraOTAStoreApplicationBundle:Admin/Build:getFile' }

majoraotastore_admin_build_toggle_enable:
    path:     '/{id}/enable'
    defaults: { _controller: 'MajoraOTAStoreApplicationBundle:Admin/Build:toggleEnable' }
