AppBuild\Bundle\ApplicationBundle\Entity\Application:
    constraints:
        - Callback: [validate]
    properties:
        support:
            - Choice:
                callback: getAvailableSupports
