language: php

php:
  - 5.6

before_script:
  - gem install sass
  - make test-prepare

script:
  - bin/phpunit -c app --testsuite majoraotastore_project --coverage-clover=coverage.clover
  - bin/behat --no-interaction
