imports:
    - { resource: 'parameters.yml' }
    - { resource: 'security.yml' }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

    # Locales
    routing_locales: '(fr|en)'
    enabled_locales: ['fr', 'en']

    # Web
    web_builds_application_dir: '%kernel.root_dir%/../web/%web_relative_builds_application_dir%'

framework:
    translator:
        fallbacks: ['%default_locale%']
    default_locale: '%default_locale%'
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: false }
    templating:
        engines: ['twig']
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: 'session.handler.native_file'
        save_path: '%session_save_path%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'
    globals:
        timezone: '%timezone%'
        use_webpack_dev_server: '%use_webpack_dev_server%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: 'pdo_mysql'
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: 'UTF8'
        server_version: '%database_server_version%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: 'doctrine.orm.naming_strategy.underscore'
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: 'memory' }

# Doctrine behaviors
stof_doctrine_extensions:
    default_locale: '%default_locale%'
    orm:
        default:
            timestampable: true
            sluggable: true

bazinga_js_translation:
    active_locales: '%enabled_locales%'
    locale_fallback: '%default_locale%'
