user_name: vagrant
projects_dir: /var/www/
ssh_key: ~/.ssh/id_rsa
workspace: /home/vagrant
ruby_download_url: https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.3.tar.gz
ruby_version: 2.2.3

pools:
  - { name: 'www', user: 'vagrant', group: 'vagrant', listen: '127.0.0.1:9000' }

php:
  memory_limit: 2G
  extensions:
    - php5-fpm
    - php5-cli
    - php5-imap
    - php5-curl
    - php5-intl
    - php5-gd
    - php5-mcrypt
    - php5-mysql
    - php5-json
    - php5-sqlite
    - php5-xdebug

sites:
  - { name: 'appbuild', docroot: '/var/www/AppBuildServer', server_name: '*.app-build.dev' }

mysql:
  databases:
    - { name: 'appbuild' }

  users:
    - { name: 'appbuild', host: '%' }

  bind_address: 0.0.0.0
