
# Builds
appbuild_admin_build_list:
    path:     /
    defaults: { _controller: AppBuildApplicationBundle:Build:list }

appbuild_admin_build_create:
    path:     /create
    defaults: { _controller: AppBuildApplicationBundle:Build:create }

appbuild_admin_build_update:
    path:     /{id}/update
    defaults: { _controller: AppBuildApplicationBundle:Build:update }

appbuild_admin_build_delete:
    path:     /{id}/delete
    defaults: { _controller: AppBuildApplicationBundle:Build:delete }

appbuild_admin_build_download:
    path:     /{id}/download
    defaults: { _controller: AppBuildApplicationBundle:Build:download }

appbuild_admin_build_get_manifest:
    path:     /{id}/manifest
    defaults: { _controller: AppBuildApplicationBundle:Build:getManifest }

appbuild_admin_build_get_raw_file:
    path:     /{id}/file
    defaults: { _controller: AppBuildApplicationBundle:Build:getRawFile }
