---

workspace: '/var/www/MajoraOTAStore'

sites:
  - { name: 'MajoraOTAStore', server_name: 'majoraotastore.dev', template: 'vhost.symfony.j2', client_max_body_size: '1024M' }

mysql:
  users:
    - { name: 'root', password: '' }
  databases:
    - { name: 'majoraotastore' }

php_versions: ['5.6']
php_upload_max_filesize: '1024M'
php_post_max_size: '1024M'

capistrano_version: '3.6.1'
