---
elasticsearch:
  url: 'http://download.elasticsearch.org/elasticsearch/elasticsearch'
  deb:
    package: 'elasticsearch-1.0.0.deb'
    service: 'elasticsearch'
    dependencies:
      - 'openjdk-6-jre'
      - 'openjdk-6-jdk'
  plugin: '/usr/share/elasticsearch/bin/plugin'
  config: '/etc/elasticsearch/elasticsearch.yml'

  tmp: '/tmp'
